# Nome del modello Hugging Face da caricare.
# Assicurati che questo modello sia disponibile localmente o scaricabile.
model_name: /home/tiziano/langgraph_agents/NER_annotator_agent/local_llm/fine_tuned_mistral_ner_model_v1.3

# Parametri di generazione del modello
# *** MODIFICHE SUGGERITE QUI ***
temperature: 0.05           # Abbassato drasticamente per un output quasi deterministico.
max_output_tokens: 600     # Numero massimo di nuovi token da generare per risposta (puoi aumentarlo se il JSON è molto lungo).
top_p: 0.5
top_k: 10
do_sample: False           # <<< CRUCIALE: Impostato a False per un output deterministico (greedy decoding).
repetition_penalty: 1.11   # Valore tipico, puoi adattarlo.
# num_beams: 1           # Non necessario se do_sample è False e non usi beam search.

# Tipo di dato per il caricamento del modello (es. "bfloat16", "float16", "float32")
# Assicurati che sia compatibile con la tua GPU e il modello.
torch_dtype: "bfloat16"

# Aggiungi i token di istruzione e il contenuto del prompt nel config loader per il MistralLoader
START_INSTRUCTION_TOKEN: "<s>[INST]"
END_INSTRUCTION_TOKEN: "[/INST]"


# Dimensione del contesto (non direttamente usato da HuggingFacePipeline per il controllo del contesto LLM,
# ma può essere usato dalla tua logica Preprocessor o per documentazione)
n_ctx: 4096

TENDER_PROMPT: >
 <SCENARIO>
  You are an NER agent for Slovenian tender documents (noisy, OCR-derived text).
  Output a JSON array per the schema.
  </SCENARIO>

  <RULES>
  Adapt values for OCR errors. Skip missing entities; do not hallucinate.
  Note chunk index:
  - chunk_id = 0: usually resides above the totality of the fields
  - chunk_id = 1: usually resides only names and deadlines, often empty
  - Avoid repetitive occurrences.
  </RULES>

  <SCHEMA>
  TENDER ID Fields (usually contiguous):
  - TenderType: (n=non-medical, m=medical, x=services). Infer if missing from goods/services in chunk; ignore if none. 'm'/'x' often require inference.
  - TenderYear: four-digit year
  - TenderNumber: string int between 000 and 999
  - TenderCode: code in the format 'aa/bb' or 'aaa/bb' or only 'aa', regex: ^[a-z]{2,3}(/[a-z]{2})?$ 

  TENDER Fields:
  - TenderPerson: name like "firstname lastname", may appear "firstname.lastnameOtherWords" (correct dots/irregularities)
  - TenderOrg: free-text organization name, preserve OCR text
  - TenderTel, TenderFax: phone numbers, format as examples (e.g. "(03) 42 33 000").
  - TenderDeadline: date in format dd.mm.yyyy
  </SCHEMA>

  <FORMAT>
  Output Format: List[Dict[str, str]] or empty list.
  Return:
  [] if no relevant entity is found
  Otherwise, a list of dictionaries as follows:
  [ ...
  { "TenderNumber": "309" },
  { "TenderDeadline":"28.04.2023" },
  ...
  ]
  </FORMAT>

  <EXAMPLES>

  Input:
  chunk_id: 0
  splosna bolnisnica celje oblakova ulica 5 3000 celje tel (03) 42 33 000 fax: (03) 42 33 757 postopek 309 2022 da/vh povabilo k oddaji ponudbe narocnik vabi ponudnike
  Output:
  [
  { "TenderOrg": "splosna bolnisnica celje" },
  { "TenderTel": "(03) 42 33 000" },
  { "TenderFax": "(03) 42 33 757" },
  { "TenderNumber": "309" },
  { "TenderYear": "2022" },
  { "TenderCode": "da/vh" },
  ]

  Example 1
  Input:
  chunk_id: 0
  postopek 165 2023 da/sp povabilo k oddaji ponudbe narocnik vabi ponudnike da v skladu z navodili ponudnikom izdelajo ponudbo za popravilo centrifuge heraeus cryofuge 6000 naziv aparata centrifuga proizvajalec heraeus tip cryofuge 6000 inv.st. kljuke za oddelcne lekarne do najkasneje 28.04.2023 do 12 ure. vodja nabavne sluzbe matjaz stinek.) univ.dipl.ekon
  Output:
  [
  { "TenderNumber": "165" },
  { "TenderYear": "2023" },
  { "TenderCode": "da/sp" },
  { "TenderDeadline": "28.04.2023" },
  { "TenderPerson": "matjaz stinek" },
  { "TenderType": "x"} 
  ]

  Example 2 (with dotted name, spacing in deadline, single non medical good)
  Input:
  chunk_id: 0
  en n 123 2022 sp/hv rok za oddajo 10. 07. 2024 kontaktna oseba ana.novak odgovorna oseba ana.novak predmet javnega narocila: dobava pisarniskega materiala tonerjev in pisal
  Output:
  [
  { "TenderNumber": "123" },
  { "TenderYear": "2022" },
  { "TenderCode": "sp/hv" },
  { "TenderDeadline": "10.07.2024" },
  { "TenderPerson": "ana novak" },
  { "TenderType": "n" }
  ]

  Example 3
  Input:
  chunk_id: 0
  dokumentacija za postopek 045 2023 mvk/vh mora biti predlozena pravocasno za dobavo ultrazvocnih gelov
  Output:
  [
  { "TenderNumber": "45" },
  { "TenderYear":"2023" },
  { "TenderCode":"mvk/vh" },
  { "TenderType": "m" }
  ]

  Example 4 (no one match)
  Input:
  chunk_id: 1 
  navodila za uporabo opreme sono navedena in prilozenem dokumentu. pred montazo jih natancno preberite
  Output:
  []

  Example 5 (no ID, multiple non-contiguous goods/services)
  Input:
  chunk_id: 1 
  kontaktna oseba luka.zajc predmet javnega narocila je najem tiskalnikov per un periodo di tre anni. poleg tega bo izvedena tudi dobava kartus in papirja za vse oddelke.
  Output:
  [
  { "TenderPerson": "luka zajc" },
  ]
  </EXAMPLES>
