model_name: "gemma-3-12b-it-Q8_0.gguf"
model_directory: "./local_llm"
#grammar_path: "./config/JSONgrammar.gbnf"
grammar_path: null
n_gpu_layers: -1
n_ctx: 4096
n_batch: 1024
verbose: false
repeat_penalty: 1.12
temperature: 0.2
top_k: 20
top_p: 0.50
streaming: false

user_input_limit: 4000