# config/default_config.yml

TOPIC: "linking"
LANG: "sl"

DATA_PATH: "./data/input/{TOPIC}_data.jsonl"
LABELS_PATH: "./data/input/labels/"

OUTPUT_PATH: "./data/output/{TOPIC}_dataset.jsonl"
CHECKPOINT_PATH: "./data/checkpoint/{TOPIC}_checkpoint.json"

PROMPTS_PATH: "./prompt/linking_prompts.yml"
MODEL_CONFIG: "./config/gemini2.0-flash.yml"